/********************************************************************************
*Author :       explorersoftware.taobao.com 
*Time   :       2017-3-30 09:19:37
*Explain:       
*
********************************************************************************/



#ifndef __BAT_H
#define __BAT_H

#include "UHEAD.H"
#include "stm8l15x_adc.h"
#include "ADC_CHECK.H"

uint16_t Get_BAT_ADC_Dat(hardChannel hard_channel);


#endif
